"""
Django settings for Reddit_site project.

Generated by 'django-admin startproject' using Django 2.0.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from environs import Env

from django.contrib.messages import constants as messages



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True
ALLOWED_HOSTS = ['198.211.101.234', '127.0.0.1', 'localhost', '162.158.63.166', 'fandeed.com', '.ngrok.io']
# Application definition
SECRET_KEY = "2mcwwq0sbjyw0t2#b&egw5r!cy@ae%92yc89_e=t0!bk6cz%br"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'Reddit_app',
    'crispy_forms',
    'phonenumber_field',
    'sorl.thumbnail',
    'social_django',
    'bootstrap4',
    'django_celery_results',
    'django_celery_beat',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'social_django.middleware.SocialAuthExceptionMiddleware',
    'django_plotly_dash.middleware.BaseMiddleware',
]

ROOT_URLCONF = 'Reddit_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                #'social_django.context_processors.backends',
                #'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'Reddit_site.wsgi.application'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

'''  online'''
'''  Atlas '''
# old one"host": "mongodb+srv://odinask:Bluetick.group2020@cluster0.pgvti.mongodb.net/Nat_Flowers?retryWrites=true&w=majority",

DATABASES = {
    'default': {
        "ENGINE": "djongo",
        "CLIENT": {
        "host": "mongodb://odinask:Bluetick.group2020@198.211.101.234:27017/db?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false",
        "username": "odinask",
        "password": "Bluetick.group2020",
        "name": "fandeed",
        "authSource": "admin",
    },
}}

'''official server MongoDB '''
"""
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        "CLIENT": {
            #"host":"198.211.101.234",
            "host": "127.0.0.1",
            "port": 27017,
            "name": "reddit_django"
            #"username": "odinask",
            #"password": "Bluetick.group2020",
            #"name": "fandeed",
            #"authSource": "admin",
        }
    },
}
"""
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True

X_FRAME_OPTIONS = 'SAMEORIGIN'

PHONENUMBER_DB_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "US"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    BASE_DIR + "/plugin",
]

# commenting out for local host


CRISPY_TEMPLATE_PACK = "bootstrap4"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
print("media root is ", MEDIA_ROOT)
MEDIA_URL = '/media/'

LOGIN_URL = '/accounts/login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (  # new
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (  # new
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    # 'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

#SOCIAL_AUTH_STRATEGY = 'social_django.strategy.DjangoStrategy'  # new
#SOCIAL_AUTH_STORAGE = 'social_django.models.DjangoStorage'  # new

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '1035962500067-0s87tiek18huuis2fo97hi8903r9gjce.apps.googleusercontent.com'  # new
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'MigGDKtZ74N-gB3YVQzmrSqI'  # new


def verified_callback(user):
    user.is_active = True



# For Django Email Backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'erpsystem.msg@gmail.com'
EMAIL_HOST_PASSWORD = 'ERPSYSTEM1'  # os.environ['password_key'] suggested
EMAIL_USE_TLS = True

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = True

APPEND_SLASH = True
# CKEDITOR_RESTRICT_BY_USER=True

# available toobar
# {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'Undo', 'Redo','Bold', 'Italic', 'Underline','EasyImageUpload','Embed']},

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'Undo', 'Redo', 'Bold', 'Italic', 'Underline','EasyImageUpload']},
        ],
        'toolbar': 'YourCustomToolbarConfig',
        'width': 'auto',
        'tabSpaces': 4,
        'removePlugins': 'image',
        'extraPlugins': ','.join([
            'easyimage',  # the upload image feature
            'div',
            'autolink',
            #'autoembed',
            'embed',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

# for twilio sms
TWILIO_ACCOUNT_SID = 'AC19208f0127609bf5b16f4c7e1ff4a072'
TWILIO_AUTH_TOKEN = '123c8f75eec6880f948023f063516c08'
CENTRAL_NUMBER = "+12055579149"
SMS_BROADCAST_TO_NUMBERS = [
    "+13473639718",  # use the format +19735551234
]
REDIS_HOST = '0.0.0.0'
REDIS_PORT = '6379'
CELERY_BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'US/Eastern'
# BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'django-db'

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
)

APPEND_SLASH=True